import { memo } from 'react';
import type { AnalysisSource } from '../types/legal';

interface AnalysisSourceBadgeProps {
  source?: AnalysisSource;
  model?: string;
}

/** Discloses whether content came from Google Gemini or the offline statutory rule engine. */
export const AnalysisSourceBadge = memo<AnalysisSourceBadgeProps>(function AnalysisSourceBadge({ source, model }) {
  if (source === 'genai') {
    return (
      <span className="source-badge source-genai" title={model ? `Generated by ${model}; quotes and citations verified` : undefined}>
        Gemini GenAI · grounded
      </span>
    );
  }
  if (source === 'rules') {
    return <span className="source-badge source-rules">Statutory rule engine</span>;
  }
  return <span className="source-badge source-curated">Curated expert analysis</span>;
});
