import React from 'react';
import { CloseIcon, ShieldAlertIcon } from './Icons';

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="modal-folio modal-folio-large" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="modal-title-group">
            <ShieldAlertIcon size={18} />
            <h2>TERMS OF SERVICE AND LEGAL NOTICE</h2>
          </div>
          <button type="button" onClick={onClose} className="modal-close-btn" aria-label="Close dialog">
            <CloseIcon size={16} />
          </button>
        </div>

        <div className="modal-body policy-text-body">
          <div className="policy-statutory-callout">
            <strong>CRITICAL LEGAL DISCLAIMER:</strong> JurisFolio is an algorithmic legal information and document analysis tool. JurisFolio is not a law firm, does not engage in the practice of law, and does not provide legal advice or legal representation. Use of this application does not create an attorney-client relationship under any jurisdiction.
          </div>

          <section className="policy-section">
            <h3>1. Informational Purpose Only</h3>
            <p>
              All analyses, risk classifications, plain-language summaries, counter-proposal redlines, and case law citations generated by JurisFolio are intended strictly for educational, informational, and preliminary document preparation purposes. They do not substitute for customized advice from an advocate or attorney licensed in your jurisdiction.
            </p>
          </section>

          <section className="policy-section">
            <h3>2. User Representations and Document Rights</h3>
            <p>
              By submitting or pasting documents into JurisFolio, you represent and warrant that you hold lawful authorization to access and review said documents, and that such ingestion does not violate third-party confidentiality agreements, protective court orders, or statutory trade secret protections.
            </p>
          </section>

          <section className="policy-section">
            <h3>3. No Warranty on Statutory Currency</h3>
            <p>
              While JurisFolio references landmark judicial precedents from the Supreme Court and High Courts, statutory frameworks and local rules vary significantly by jurisdiction, court district, and legislative amendments. The software is provided on an "as is" and "as available" basis without warranties of merchantability, fitness for a particular purpose, or statutory completeness.
            </p>
          </section>

          <section className="policy-section">
            <h3>4. Limitation of Liability</h3>
            <p>
              Under no circumstances shall JurisFolio, its creators, developers, or affiliates be liable for any direct, indirect, incidental, punitive, or consequential damages arising from reliance upon automated outputs, contract redlines, or decisions taken regarding contractual negotiations or litigation.
            </p>
          </section>

          <section className="policy-section">
            <h3>5. Dispute Resolution and Governing Framework</h3>
            <p>
              Any controversy relating to these Terms of Service shall be governed by and construed in accordance with the substantive laws of the relevant jurisdiction, without regard to conflict of laws principles.
            </p>
          </section>
        </div>

        <div className="modal-actions-bar">
          <button type="button" onClick={onClose} className="action-btn-primary">
            I Understand and Acknowledge
          </button>
        </div>
      </div>
    </div>
  );
};
